"""
Django settings for openplatform project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')k03qpa39p%dd#=p3i05!3s_1l$ru!%m9iur!-j$3e8vy(-@h9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
ALLOWED_CORS_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bixin',
    'account',
    'assets',
    'servicer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',

    'bixin.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'openplatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['bixin.templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.static',
            ]
        },
    },
]

WSGI_APPLICATION = 'openplatform.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'yourdatabasename.db'),
        'ATOMIC_REQUESTS': True,
        'CONN_MAX_AGE': 100
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'

DOMAIN_NAME = 'platformdemo.bixin.im'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend']

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': sys.stdout,
        },
        'syslog': {
            'class': 'logging.handlers.SysLogHandler',
            'formatter': 'remote',
            'address': ('localhost', 514),
            'facility': 'local0',
        }
    },
    'formatters':{
        'simple':{
            'format': '%(asctime)s %(name)s [%(levelname)s] %(message)s',
        },
        'remote':{
            'format': '%(name)s:%(message)s',
        },
    },
    'root': {
        'handlers': ['console', 'syslog'],
        'level': 'INFO'
    },
}


PLATFORM_SERVER = 'https://bixin.im'
QR_LOGIN_URL = 'https://login.bixin.im'
BIXIN_APP_HOST = 'https://openapi.bixin.im'

APP_NAME = ''
VENDOR_SECRET = ''
VENDOR_AES_KEY = ''
BOT_ACCESS_TOKEN = ''
BOT_AES_KEY = ''
JS_SDK_CALLBACK = ''

try:
    from local_settings import *
except ImportError:
    pass
